import { readdirSync, writeFileSync } from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const header = "//This file is auto-generated by running `lib/findIcons.js`. Please do not edit it manually.\n";
const resolve = (path) => fileURLToPath(import.meta.resolve(path));
const icons = readdirSync(resolve("../app/assets/images/icons/")).flatMap(
  (name) => name.slice(0, -path.extname(name).length) || [],
);
writeFileSync(resolve("../app/javascript/stylesheets/_icon_names.scss"), `${header}$icons: ["${icons.join('","')}"];`);
writeFileSync(resolve("../app/javascript/types/icons.d.ts"), `${header}type IconName = "${icons.join('"|"')}";`);
