# frozen_string_literal: true

return if ENV["SKIP_TAXONOMY_CREATION"] == "1"
return if Taxonomy.where(slug: "3d").exists?

three_d = Taxonomy.find_or_create_by!(slug: "3d")
Taxonomy.find_or_create_by!(slug: "3d-modeling", parent: three_d)
Taxonomy.find_or_create_by!(slug: "character-design", parent: three_d)
Taxonomy.find_or_create_by!(slug: "rigging", parent: three_d)
Taxonomy.find_or_create_by!(slug: "animating", parent: three_d)
ar = Taxonomy.find_or_create_by!(slug: "arvr", parent: three_d)
Taxonomy.find_or_create_by!(slug: "spark-ar-studio", parent: ar)
three_d_assets = Taxonomy.find_or_create_by!(slug: "3d-assets", parent: three_d)
Taxonomy.find_or_create_by!(slug: "blender", parent: three_d_assets)
Taxonomy.find_or_create_by!(slug: "maya", parent: three_d_assets)
Taxonomy.find_or_create_by!(slug: "modo", parent: three_d_assets)
Taxonomy.find_or_create_by!(slug: "cinema-4d", parent: three_d_assets)
unity = Taxonomy.find_or_create_by!(slug: "unity", parent: three_d_assets)
Taxonomy.find_or_create_by!(slug: "sketchup", parent: three_d_assets)
Taxonomy.find_or_create_by!(slug: "unreal-engine", parent: three_d_assets)
Taxonomy.find_or_create_by!(slug: "3dsmax", parent: three_d_assets)
Taxonomy.find_or_create_by!(slug: "zbrush", parent: three_d_assets)

design = Taxonomy.find_or_create_by!(slug: "design")
Taxonomy.find_or_create_by!(slug: "industrial-design", parent: design)
Taxonomy.find_or_create_by!(slug: "entertainment-design", parent: design)
Taxonomy.find_or_create_by!(slug: "architecture", parent: design)
Taxonomy.find_or_create_by!(slug: "fashion-design", parent: design)
Taxonomy.find_or_create_by!(slug: "interior-design", parent: design)
web = Taxonomy.find_or_create_by!(slug: "ui-and-web", parent: design)
Taxonomy.find_or_create_by!(slug: "figma", parent: web)
Taxonomy.find_or_create_by!(slug: "xd", parent: web)
Taxonomy.find_or_create_by!(slug: "adobe", parent: web)
Taxonomy.find_or_create_by!(slug: "html", parent: web)
packaging = Taxonomy.find_or_create_by!(slug: "print-and-packaging", parent: design)
Taxonomy.find_or_create_by!(slug: "canva", parent: packaging)
Taxonomy.find_or_create_by!(slug: "illustrator", parent: packaging)
Taxonomy.find_or_create_by!(slug: "powerpoint", parent: packaging)
Taxonomy.find_or_create_by!(slug: "indesign", parent: packaging)
graphics = Taxonomy.find_or_create_by!(slug: "graphics", parent: design)
Taxonomy.find_or_create_by!(slug: "textures-and-patterns-2d", parent: graphics)
Taxonomy.find_or_create_by!(slug: "vector-graphics", parent: graphics)
Taxonomy.find_or_create_by!(slug: "marketing-and-social", parent: graphics)
Taxonomy.find_or_create_by!(slug: "assets-and-templates", parent: graphics)
mockups = Taxonomy.find_or_create_by!(slug: "mockups", parent: graphics)
Taxonomy.find_or_create_by!(slug: "photoshop", parent: mockups)
Taxonomy.find_or_create_by!(slug: "illustrator", parent: mockups)
Taxonomy.find_or_create_by!(slug: "canva", parent: mockups)
Taxonomy.find_or_create_by!(slug: "indesign", parent: mockups)
Taxonomy.find_or_create_by!(slug: "fonts", parent: design)
branding = Taxonomy.find_or_create_by!(slug: "branding", parent: design)
Taxonomy.find_or_create_by!(slug: "logos", parent: branding)
Taxonomy.find_or_create_by!(slug: "business-cards", parent: branding)
Taxonomy.find_or_create_by!(slug: "social-media", parent: branding)
Taxonomy.find_or_create_by!(slug: "wallpapers", parent: design)
icons = Taxonomy.find_or_create_by!(slug: "icons", parent: design)
Taxonomy.find_or_create_by!(slug: "3d-icons", parent: icons)
Taxonomy.find_or_create_by!(slug: "vector-icons", parent: icons)
Taxonomy.find_or_create_by!(slug: "ios-customization", parent: icons)

drawing = Taxonomy.find_or_create_by!(slug: "drawing-and-painting")
illustration = Taxonomy.find_or_create_by!(slug: "digital-illustration", parent: drawing)
Taxonomy.find_or_create_by!(slug: "courses", parent: illustration)
Taxonomy.find_or_create_by!(slug: "illustration-textures-and-patterns", parent: illustration)
Taxonomy.find_or_create_by!(slug: "illustration-kits", parent: illustration)
illbrushes = Taxonomy.find_or_create_by!(slug: "illustration-brushes", parent: illustration)
Taxonomy.find_or_create_by!(slug: "photoshop", parent: illbrushes)
Taxonomy.find_or_create_by!(slug: "procreate", parent: illbrushes)
Taxonomy.find_or_create_by!(slug: "blender", parent: illbrushes)
Taxonomy.find_or_create_by!(slug: "traditional-art", parent: drawing)
Taxonomy.find_or_create_by!(slug: "artwork-and-commissions", parent: drawing)

software_development = Taxonomy.find_or_create_by!(slug: "software-development")
programming = Taxonomy.find_or_create_by!(slug: "programming", parent: software_development)
Taxonomy.find_or_create_by!(slug: "c-sharp", parent: programming)
Taxonomy.find_or_create_by!(slug: "python", parent: programming)
web = Taxonomy.find_or_create_by!(slug: "web-development", parent: software_development)
Taxonomy.find_or_create_by!(slug: "aws", parent: web)
Taxonomy.find_or_create_by!(slug: "ruby", parent: web)
js = Taxonomy.find_or_create_by!(slug: "javascript", parent: web)
Taxonomy.find_or_create_by!(slug: "react-js", parent: js)
mobile = Taxonomy.find_or_create_by!(slug: "app-development", parent: software_development)
Taxonomy.find_or_create_by!(slug: "swift", parent: mobile)
Taxonomy.find_or_create_by!(slug: "react-native", parent: mobile)
software = Taxonomy.find_or_create_by!(slug: "software-and-plugins", parent: software_development)
Taxonomy.find_or_create_by!(slug: "wordpress", parent: software)
Taxonomy.find_or_create_by!(slug: "vscode", parent: software)
hardware = Taxonomy.find_or_create_by!(slug: "hardware", parent: software_development)
Taxonomy.find_or_create_by!(slug: "raspberry-pi", parent: hardware)

self_improvement = Taxonomy.find_or_create_by!(slug: "self-improvement")
Taxonomy.find_or_create_by!(slug: "psychology", parent: self_improvement)
Taxonomy.find_or_create_by!(slug: "productivity", parent: self_improvement)
Taxonomy.find_or_create_by!(slug: "dating-and-relationships", parent: self_improvement)
Taxonomy.find_or_create_by!(slug: "philosophy", parent: self_improvement)
spirituality = Taxonomy.find_or_create_by!(slug: "spirituality", parent: self_improvement)
Taxonomy.find_or_create_by!(slug: "astrology", parent: spirituality)
Taxonomy.find_or_create_by!(slug: "meditation", parent: spirituality)
Taxonomy.find_or_create_by!(slug: "magic", parent: spirituality)
mysticism = Taxonomy.find_or_create_by!(slug: "mysticism", parent: spirituality)
Taxonomy.find_or_create_by!(slug: "tarot", parent: mysticism)
Taxonomy.find_or_create_by!(slug: "wicca-witchcraft-and-paganism", parent: spirituality)
cooking = Taxonomy.find_or_create_by!(slug: "cooking", parent: self_improvement)
Taxonomy.find_or_create_by!(slug: "nutrition", parent: cooking)
Taxonomy.find_or_create_by!(slug: "vegan", parent: cooking)
Taxonomy.find_or_create_by!(slug: "recipes", parent: cooking)
crafts = Taxonomy.find_or_create_by!(slug: "crafts-and-dyi", parent: self_improvement)
Taxonomy.find_or_create_by!(slug: "papercrafts", parent: crafts)
Taxonomy.find_or_create_by!(slug: "crafts-for-children", parent: crafts)
Taxonomy.find_or_create_by!(slug: "jewelry", parent: crafts)
Taxonomy.find_or_create_by!(slug: "lego", parent: crafts)
Taxonomy.find_or_create_by!(slug: "3d-printing", parent: crafts)
Taxonomy.find_or_create_by!(slug: "board-games", parent: crafts)
sewing = Taxonomy.find_or_create_by!(slug: "sewing", parent: crafts)
Taxonomy.find_or_create_by!(slug: "courses", parent: sewing)
Taxonomy.find_or_create_by!(slug: "kits", parent: sewing)
woodworking = Taxonomy.find_or_create_by!(slug: "woodworking", parent: crafts)
Taxonomy.find_or_create_by!(slug: "courses", parent: woodworking)
Taxonomy.find_or_create_by!(slug: "kits", parent: woodworking)
Taxonomy.find_or_create_by!(slug: "automotive", parent: crafts)
Taxonomy.find_or_create_by!(slug: "wellness", parent: self_improvement)
Taxonomy.find_or_create_by!(slug: "weddings", parent: self_improvement)
Taxonomy.find_or_create_by!(slug: "travel", parent: self_improvement)
outdoors = Taxonomy.find_or_create_by!(slug: "outdoors", parent: self_improvement)
Taxonomy.find_or_create_by!(slug: "trekking", parent: outdoors)
Taxonomy.find_or_create_by!(slug: "hunting", parent: outdoors)
Taxonomy.find_or_create_by!(slug: "boating-and-fishing", parent: outdoors)

fitness = Taxonomy.find_or_create_by!(slug: "fitness-and-health")
Taxonomy.find_or_create_by!(slug: "sports", parent: fitness)
Taxonomy.find_or_create_by!(slug: "exercise-and-workout", parent: fitness)
Taxonomy.find_or_create_by!(slug: "running", parent: fitness)
Taxonomy.find_or_create_by!(slug: "weight-loss-and-dieting", parent: fitness)
Taxonomy.find_or_create_by!(slug: "yoga", parent: fitness)

music = Taxonomy.find_or_create_by!(slug: "music-and-sound-design")
instruments = Taxonomy.find_or_create_by!(slug: "instruments", parent: music)
Taxonomy.find_or_create_by!(slug: "guitar", parent: instruments)
Taxonomy.find_or_create_by!(slug: "piano", parent: instruments)
Taxonomy.find_or_create_by!(slug: "vocal", parent: music)
dance = Taxonomy.find_or_create_by!(slug: "dance-and-theater", parent: music)
Taxonomy.find_or_create_by!(slug: "dance", parent: dance)
Taxonomy.find_or_create_by!(slug: "theater", parent: dance)
sounddesign = Taxonomy.find_or_create_by!(slug: "sound-design", parent: music)
Taxonomy.find_or_create_by!(slug: "courses", parent: sounddesign)
Taxonomy.find_or_create_by!(slug: "samples", parent: sounddesign)
Taxonomy.find_or_create_by!(slug: "sheet-music", parent: sounddesign)
sdplugins = Taxonomy.find_or_create_by!(slug: "plugins", parent: sounddesign)
Taxonomy.find_or_create_by!(slug: "ableton-live", parent: sdplugins)
Taxonomy.find_or_create_by!(slug: "fl-studio", parent: sdplugins)
Taxonomy.find_or_create_by!(slug: "logic-pro", parent: sdplugins)

photography = Taxonomy.find_or_create_by!(slug: "photography")
Taxonomy.find_or_create_by!(slug: "photo-presets-and-actions", parent: photography)
Taxonomy.find_or_create_by!(slug: "reference-photos", parent: photography)
Taxonomy.find_or_create_by!(slug: "stock-photos", parent: photography)
Taxonomy.find_or_create_by!(slug: "photo-courses", parent: photography)
Taxonomy.find_or_create_by!(slug: "cosplay", parent: photography)

writing = Taxonomy.find_or_create_by!(slug: "writing-and-publishing")
Taxonomy.find_or_create_by!(slug: "courses", parent: writing)
Taxonomy.find_or_create_by!(slug: "resources", parent: writing)

business = Taxonomy.find_or_create_by!(slug: "business-and-money")
Taxonomy.find_or_create_by!(slug: "accounting", parent: business)
Taxonomy.find_or_create_by!(slug: "investing", parent: business)
Taxonomy.find_or_create_by!(slug: "personal-finance", parent: business)
marketing = Taxonomy.find_or_create_by!(slug: "marketing-and-sales", parent: business)
Taxonomy.find_or_create_by!(slug: "email", parent: marketing)
Taxonomy.find_or_create_by!(slug: "social-media", parent: marketing)
Taxonomy.find_or_create_by!(slug: "analytics", parent: marketing)
Taxonomy.find_or_create_by!(slug: "networking-careers-and-jobs", parent: business)
Taxonomy.find_or_create_by!(slug: "management-and-leadership", parent: business)
Taxonomy.find_or_create_by!(slug: "real-estate", parent: business)
Taxonomy.find_or_create_by!(slug: "gigs-and-side-projects", parent: business)
entrepreneurship = Taxonomy.find_or_create_by!(slug: "entrepreneurship", parent: business)
Taxonomy.find_or_create_by!(slug: "resources", parent: entrepreneurship)
Taxonomy.find_or_create_by!(slug: "courses", parent: entrepreneurship)
Taxonomy.find_or_create_by!(slug: "podcasts", parent: entrepreneurship)

education = Taxonomy.find_or_create_by!(slug: "education")
Taxonomy.find_or_create_by!(slug: "classroom", parent: education)
Taxonomy.find_or_create_by!(slug: "test-prep", parent: education)
sstudies = Taxonomy.find_or_create_by!(slug: "social-studies", parent: education)
Taxonomy.find_or_create_by!(slug: "history", parent: sstudies)
Taxonomy.find_or_create_by!(slug: "politics", parent: sstudies)
Taxonomy.find_or_create_by!(slug: "law", parent: sstudies)
Taxonomy.find_or_create_by!(slug: "english", parent: education)
Taxonomy.find_or_create_by!(slug: "history", parent: education)
Taxonomy.find_or_create_by!(slug: "math", parent: education)
science = Taxonomy.find_or_create_by!(slug: "science", parent: education)
Taxonomy.find_or_create_by!(slug: "medicine", parent: science)
Taxonomy.find_or_create_by!(slug: "specialties", parent: education)

# Listen

Taxonomy.find_or_create_by!(slug: "comics-and-graphic-novels")

fiction = Taxonomy.find_or_create_by!(slug: "fiction-books")
Taxonomy.find_or_create_by!(slug: "childrens-books", parent: fiction)
Taxonomy.find_or_create_by!(slug: "teen-and-young-adult", parent: fiction)
Taxonomy.find_or_create_by!(slug: "fantasy", parent: fiction)
Taxonomy.find_or_create_by!(slug: "science-fiction", parent: fiction)
Taxonomy.find_or_create_by!(slug: "romance", parent: fiction)
Taxonomy.find_or_create_by!(slug: "mystery", parent: fiction)

audio = Taxonomy.find_or_create_by!(slug: "audio")
Taxonomy.find_or_create_by!(slug: "hypnosis", parent: audio)
Taxonomy.find_or_create_by!(slug: "subliminal-messages", parent: audio)
Taxonomy.find_or_create_by!(slug: "healing", parent: audio)
Taxonomy.find_or_create_by!(slug: "sleep-and-meditation", parent: audio)
Taxonomy.find_or_create_by!(slug: "asmr", parent: audio)
Taxonomy.find_or_create_by!(slug: "voiceover", parent: audio)

music = Taxonomy.find_or_create_by!(slug: "recorded-music")
Taxonomy.find_or_create_by!(slug: "albums", parent: music)
singles = Taxonomy.find_or_create_by!(slug: "singles", parent: music)
Taxonomy.find_or_create_by!(slug: "alternative-and-indie", parent: singles)
Taxonomy.find_or_create_by!(slug: "rock", parent: singles)
Taxonomy.find_or_create_by!(slug: "blues", parent: singles)
Taxonomy.find_or_create_by!(slug: "broadway-and-vocalists", parent: singles)
Taxonomy.find_or_create_by!(slug: "childrens-music", parent: singles)
Taxonomy.find_or_create_by!(slug: "christian", parent: singles)
Taxonomy.find_or_create_by!(slug: "classical", parent: singles)
Taxonomy.find_or_create_by!(slug: "classic-rock", parent: singles)
Taxonomy.find_or_create_by!(slug: "comedy-and-miscellaneous", parent: singles)
Taxonomy.find_or_create_by!(slug: "country", parent: singles)
Taxonomy.find_or_create_by!(slug: "dance-and-electronic", parent: singles)
Taxonomy.find_or_create_by!(slug: "folk", parent: singles)
Taxonomy.find_or_create_by!(slug: "gospel", parent: singles)
Taxonomy.find_or_create_by!(slug: "hard-rock-and-metal", parent: singles)
Taxonomy.find_or_create_by!(slug: "holiday-music", parent: singles)
Taxonomy.find_or_create_by!(slug: "jazz", parent: singles)
Taxonomy.find_or_create_by!(slug: "latin-music", parent: singles)
Taxonomy.find_or_create_by!(slug: "new-age", parent: singles)
Taxonomy.find_or_create_by!(slug: "opera-and-vocal", parent: singles)
Taxonomy.find_or_create_by!(slug: "pop", parent: singles)
Taxonomy.find_or_create_by!(slug: "rhythm-and-blues", parent: singles)
Taxonomy.find_or_create_by!(slug: "rap-and-hip-hop", parent: singles)
Taxonomy.find_or_create_by!(slug: "soundtracks", parent: singles)
Taxonomy.find_or_create_by!(slug: "world-music", parent: singles)

# Watch

films = Taxonomy.find_or_create_by!(slug: "films")
Taxonomy.find_or_create_by!(slug: "short-film", parent: films)
Taxonomy.find_or_create_by!(slug: "documentary", parent: films)
movies = Taxonomy.find_or_create_by!(slug: "movie", parent: films)
Taxonomy.find_or_create_by!(slug: "action-and-adventure", parent: movies)
Taxonomy.find_or_create_by!(slug: "animation", parent: movies)
Taxonomy.find_or_create_by!(slug: "anime", parent: movies)
Taxonomy.find_or_create_by!(slug: "black-voices", parent: movies)
Taxonomy.find_or_create_by!(slug: "classics", parent: movies)
Taxonomy.find_or_create_by!(slug: "comedy", parent: movies)
Taxonomy.find_or_create_by!(slug: "drama", parent: movies)
Taxonomy.find_or_create_by!(slug: "faith-and-spirituality", parent: movies)
Taxonomy.find_or_create_by!(slug: "foreign-language-and-international", parent: movies)
Taxonomy.find_or_create_by!(slug: "horror", parent: movies)
Taxonomy.find_or_create_by!(slug: "indian-cinema-and-bollywood", parent: movies)
Taxonomy.find_or_create_by!(slug: "indie-and-art-house", parent: movies)
Taxonomy.find_or_create_by!(slug: "kids-and-family", parent: movies)
Taxonomy.find_or_create_by!(slug: "lgbtq", parent: movies)
Taxonomy.find_or_create_by!(slug: "music-videos-and-concerts", parent: movies)
Taxonomy.find_or_create_by!(slug: "romance", parent: movies)
Taxonomy.find_or_create_by!(slug: "science-fiction", parent: movies)
Taxonomy.find_or_create_by!(slug: "western", parent: movies)

Taxonomy.find_or_create_by!(slug: "dance", parent: films)
Taxonomy.find_or_create_by!(slug: "performance", parent: films)
Taxonomy.find_or_create_by!(slug: "theater", parent: films)
comedy = Taxonomy.find_or_create_by!(slug: "comedy", parent: films)
Taxonomy.find_or_create_by!(slug: "standup", parent: comedy)
Taxonomy.find_or_create_by!(slug: "sketch", parent: comedy)
Taxonomy.find_or_create_by!(slug: "sports-events", parent: films)

Taxonomy.find_or_create_by!(slug: "videography", parent: films)
vidprod = Taxonomy.find_or_create_by!(slug: "video-production-and-editing", parent: films)
Taxonomy.find_or_create_by!(slug: "luts", parent: vidprod)
video_assets = Taxonomy.find_or_create_by!(slug: "video-assets-and-loops", parent: vidprod)
Taxonomy.find_or_create_by!(slug: "premiere-pro", parent: video_assets)
Taxonomy.find_or_create_by!(slug: "after-effects", parent: video_assets)
Taxonomy.find_or_create_by!(slug: "cinema-4d", parent: video_assets)
Taxonomy.find_or_create_by!(slug: "stock", parent: vidprod)
Taxonomy.find_or_create_by!(slug: "courses", parent: vidprod)

gaming = Taxonomy.find_or_create_by!(slug: "gaming")
Taxonomy.find_or_create_by!(slug: "streaming", parent: gaming)
vrchat = Taxonomy.find_or_create_by!(slug: "vrchat", parent: three_d)

avatars = Taxonomy.find_or_create_by!(slug: "avatars", parent: three_d)
Taxonomy.find_or_create_by!(slug: "female", parent: avatars)
Taxonomy.find_or_create_by!(slug: "male", parent: avatars)
Taxonomy.find_or_create_by!(slug: "non-binary", parent: avatars)
Taxonomy.find_or_create_by!(slug: "optimized", parent: avatars)
Taxonomy.find_or_create_by!(slug: "quest", parent: avatars)
Taxonomy.find_or_create_by!(slug: "species", parent: avatars)

avatar_components = Taxonomy.find_or_create_by!(slug: "avatar-components", parent: three_d_assets)
Taxonomy.find_or_create_by!(slug: "bases", parent: avatar_components)
Taxonomy.find_or_create_by!(slug: "ears", parent: avatar_components)
Taxonomy.find_or_create_by!(slug: "feet", parent: avatar_components)
Taxonomy.find_or_create_by!(slug: "hair", parent: avatar_components)
Taxonomy.find_or_create_by!(slug: "heads", parent: avatar_components)
Taxonomy.find_or_create_by!(slug: "horns", parent: avatar_components)
Taxonomy.find_or_create_by!(slug: "tails", parent: avatar_components)

accessories = Taxonomy.find_or_create_by!(slug: "accessories", parent: three_d_assets)
Taxonomy.find_or_create_by!(slug: "bags", parent: accessories)
Taxonomy.find_or_create_by!(slug: "belts", parent: accessories)
Taxonomy.find_or_create_by!(slug: "chokers", parent: accessories)
Taxonomy.find_or_create_by!(slug: "gloves", parent: accessories)
Taxonomy.find_or_create_by!(slug: "harnesses", parent: accessories)
Taxonomy.find_or_create_by!(slug: "jewelry", parent: accessories)
Taxonomy.find_or_create_by!(slug: "masks", parent: accessories)
Taxonomy.find_or_create_by!(slug: "wings", parent: accessories)

clothing = Taxonomy.find_or_create_by!(slug: "clothing", parent: three_d_assets)
Taxonomy.find_or_create_by!(slug: "bodysuits", parent: clothing)
Taxonomy.find_or_create_by!(slug: "bottoms", parent: clothing)
Taxonomy.find_or_create_by!(slug: "bras", parent: clothing)
Taxonomy.find_or_create_by!(slug: "dresses", parent: clothing)
Taxonomy.find_or_create_by!(slug: "jackets", parent: clothing)
Taxonomy.find_or_create_by!(slug: "lingerie", parent: clothing)
Taxonomy.find_or_create_by!(slug: "outfits", parent: clothing)
Taxonomy.find_or_create_by!(slug: "pants", parent: clothing)
Taxonomy.find_or_create_by!(slug: "shirts", parent: clothing)
Taxonomy.find_or_create_by!(slug: "shorts", parent: clothing)
Taxonomy.find_or_create_by!(slug: "skirts", parent: clothing)
Taxonomy.find_or_create_by!(slug: "sweaters", parent: clothing)
Taxonomy.find_or_create_by!(slug: "swimsuits", parent: clothing)
Taxonomy.find_or_create_by!(slug: "tops", parent: clothing)
Taxonomy.find_or_create_by!(slug: "underwear", parent: clothing)

footwear = Taxonomy.find_or_create_by!(slug: "footwear", parent: three_d_assets)
Taxonomy.find_or_create_by!(slug: "boots", parent: footwear)
Taxonomy.find_or_create_by!(slug: "leggings", parent: footwear)
Taxonomy.find_or_create_by!(slug: "shoes", parent: footwear)
Taxonomy.find_or_create_by!(slug: "socks", parent: footwear)
Taxonomy.find_or_create_by!(slug: "stockings", parent: footwear)

headwear = Taxonomy.find_or_create_by!(slug: "headwear", parent: three_d_assets)
Taxonomy.find_or_create_by!(slug: "hats", parent: headwear)

props = Taxonomy.find_or_create_by!(slug: "props", parent: three_d_assets)
Taxonomy.find_or_create_by!(slug: "companions", parent: props)
Taxonomy.find_or_create_by!(slug: "handheld", parent: props)
Taxonomy.find_or_create_by!(slug: "plushies", parent: props)
Taxonomy.find_or_create_by!(slug: "prefabs", parent: props)
Taxonomy.find_or_create_by!(slug: "weapons", parent: props)

Taxonomy.find_or_create_by!(slug: "animations", parent: unity)
Taxonomy.find_or_create_by!(slug: "particle-systems", parent: unity)
Taxonomy.find_or_create_by!(slug: "shaders", parent: unity)
Taxonomy.find_or_create_by!(slug: "avatar-systems", parent: vrchat)
Taxonomy.find_or_create_by!(slug: "followers", parent: vrchat)
Taxonomy.find_or_create_by!(slug: "osc", parent: vrchat)
Taxonomy.find_or_create_by!(slug: "setup-scripts", parent: vrchat)
Taxonomy.find_or_create_by!(slug: "spring-joints", parent: vrchat)
Taxonomy.find_or_create_by!(slug: "tools", parent: vrchat)
Taxonomy.find_or_create_by!(slug: "world-constraints", parent: vrchat)

worlds = Taxonomy.find_or_create_by!(slug: "worlds", parent: vrchat)
Taxonomy.find_or_create_by!(slug: "assets", parent: worlds)
Taxonomy.find_or_create_by!(slug: "midi", parent: worlds)
Taxonomy.find_or_create_by!(slug: "quest", parent: worlds)
Taxonomy.find_or_create_by!(slug: "tools", parent: worlds)
Taxonomy.find_or_create_by!(slug: "udon", parent: worlds)
Taxonomy.find_or_create_by!(slug: "udon-system", parent: worlds)
Taxonomy.find_or_create_by!(slug: "udon2", parent: worlds)
Taxonomy.find_or_create_by!(slug: "tutorials-guides", parent: vrchat)

textures = Taxonomy.find_or_create_by!(slug: "textures", parent: three_d)
Taxonomy.find_or_create_by!(slug: "base", parent: textures)
Taxonomy.find_or_create_by!(slug: "eyes", parent: textures)
Taxonomy.find_or_create_by!(slug: "face", parent: textures)
Taxonomy.find_or_create_by!(slug: "icons", parent: textures)
Taxonomy.find_or_create_by!(slug: "matcap", parent: textures)
Taxonomy.find_or_create_by!(slug: "pbr", parent: textures)
Taxonomy.find_or_create_by!(slug: "tattoos", parent: textures)

Taxonomy.find_or_create_by!(slug: "other")
