# frozen_string_literal: true

module Currency
  # These currencies can be used as account's default currency and to set product prices,
  # along with creating Stripe Connect accounts and making payouts.
  CURRENCY_CHOICES.each do |currency_type, _currency_hash|
    const_set(currency_type.upcase, currency_type.downcase)
  end

  # These currencies are only used for creating Stripe Connect accounts and making payouts.
  # These cannot be used as account's default currency or to set product prices.
  # Currency conversion helpers do not support for these currencies.
  THB = "thb"
  BGN = "bgn"
  BAM = "bam"
  BDT = "bdt"
  BTN = "btn"
  LAK = "lak"
  MZN = "mzn"
  DKK = "dkk"
  HUF = "huf"
  AED = "aed"
  TTD = "ttd"
  AOA = "aoa"
  RON = "ron"
  SEK = "sek"
  MXN = "mxn"
  ARS = "ars"
  NOK = "nok"
  BWP = "bwp"
  PEN = "pen"
  VND = "vnd"
  XCD = "xcd"
  TZS = "tzs"
  NAD = "nad"
  IDR = "idr"
  CRC = "crc"
  RWF = "rwf"
  CLP = "clp"
  PKR = "pkr"
  TRY = "try"
  MAD = "mad"
  RSD = "rsd"
  KES = "kes"
  EGP = "egp"
  COP = "cop"
  SAR = "sar"
  KZT = "kzt"
  MYR = "myr"
  UYU = "uyu"
  MUR = "mur"
  JMD = "jmd"
  OMR = "omr"
  DOP = "dop"
  UZS = "uzs"
  BOB = "bob"
  TND = "tnd"
  NGN = "ngn"
  AZN = "azn"
  JOD = "jod"
  BHD = "bhd"
  ALL = "all"
  MDL = "mdl"
  MKD = "mkd"
  SVC = "svc"
  MGA = "mga"
  PYG = "pyg"
  GHS = "ghs"
  AMD = "amd"
  LKR = "lkr"
  KWD = "kwd"
  QAR = "qar"
  BSD = "bsd"
  ETB = "etb"
  BND = "bnd"
  GYD = "gyd"
  GTQ = "gtq"
  XOF = "xof"
  KHR = "khr"
  MNT = "mnt"
  XAF = "xaf"
  DZD = "dzd"
  MOP = "mop"
end
